[2022-11-04T20:02:58.828+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.TASK1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T20:02:58.874+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.TASK1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T20:02:58.876+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T20:02:58.877+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T20:02:58.879+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T20:02:58.918+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): TASK1> on 2022-05-31 00:00:00+00:00
[2022-11-04T20:02:58.932+0000] {standard_task_runner.py:55} INFO - Started process 327 to run task
[2022-11-04T20:02:58.937+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'orquestation', 'TASK1', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/5.1-orquestacion.py', '--cfg-path', '/tmp/tmp4tq0t60_']
[2022-11-04T20:02:58.938+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask TASK1
[2022-11-04T20:02:59.074+0000] {task_command.py:376} INFO - Running <TaskInstance: orquestation.TASK1 scheduled__2022-05-31T00:00:00+00:00 [running]> on host 208ed96b478a
[2022-11-04T20:02:59.266+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=orquestation
AIRFLOW_CTX_TASK_ID=TASK1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-31T00:00:00+00:00
[2022-11-04T20:02:59.269+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-04T20:02:59.272+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "SLEEP 2 && ECHO 'TASK1'"]
[2022-11-04T20:02:59.299+0000] {subprocess.py:86} INFO - Output:
[2022-11-04T20:02:59.313+0000] {subprocess.py:93} INFO - /bin/bash: line 1: SLEEP: command not found
[2022-11-04T20:02:59.314+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-04T20:02:59.341+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-04T20:02:59.351+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=orquestation, task_id=TASK1, execution_date=20220531T000000, start_date=20221104T200258, end_date=20221104T200259
[2022-11-04T20:02:59.386+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task TASK1 (Bash command failed. The command returned a non-zero exit code 127.; 327)
[2022-11-04T20:02:59.431+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-04T20:02:59.498+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-04T21:13:39.837+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:13:39.867+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:13:39.868+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:13:39.869+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T21:13:39.869+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:13:39.902+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-05-31 00:00:00+00:00
[2022-11-04T21:13:39.913+0000] {standard_task_runner.py:55} INFO - Started process 446 to run task
[2022-11-04T21:13:39.919+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'orquestation', 'task1', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/5.1-orquestacion.py', '--cfg-path', '/tmp/tmpugzp4vmt']
[2022-11-04T21:13:39.921+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask task1
[2022-11-04T21:13:40.081+0000] {task_command.py:376} INFO - Running <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [running]> on host 643e334f405f
[2022-11-04T21:14:07.435+0000] {base_job.py:232} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 204, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2961, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3039, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2775, in get
    identity_token=identity_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2878, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2022-11-04T21:27:38.002+0000] {local_task_job.py:148} ERROR - Heartbeat time limit exceeded!
[2022-11-04T21:27:38.022+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 446. PIDs of all processes in the group: [446]
[2022-11-04T21:27:38.023+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 446
[2022-11-04T21:27:38.053+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=446, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='21:13:39') (446) terminated with exit code Negsignal.SIGTERM
[2022-11-04T21:33:50.748+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:33:50.774+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:33:50.775+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:33:50.775+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T21:33:50.776+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:33:50.801+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-05-31 00:00:00+00:00
[2022-11-04T21:33:50.811+0000] {standard_task_runner.py:55} INFO - Started process 1180 to run task
[2022-11-04T21:33:50.816+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'orquestation', 'task1', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/5.1-orquestacion.py', '--cfg-path', '/tmp/tmpux5uth_5']
[2022-11-04T21:33:50.817+0000] {standard_task_runner.py:83} INFO - Job 228: Subtask task1
[2022-11-04T21:33:50.910+0000] {task_command.py:376} INFO - Running <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [running]> on host 643e334f405f
[2022-11-04T21:33:51.036+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=orquestation
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-31T00:00:00+00:00
[2022-11-04T21:33:51.038+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-04T21:33:51.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'task1'"]
[2022-11-04T21:33:51.062+0000] {subprocess.py:86} INFO - Output:
[2022-11-04T21:33:53.075+0000] {subprocess.py:93} INFO - task1
[2022-11-04T21:33:53.076+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-04T21:33:53.120+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=orquestation, task_id=task1, execution_date=20220531T000000, start_date=20221104T213350, end_date=20221104T213353
[2022-11-04T21:33:53.156+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-04T21:33:53.218+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-04T21:45:30.605+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:45:30.620+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-11-04T21:45:30.621+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:45:30.621+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T21:45:30.621+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T21:45:30.637+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-05-31 00:00:00+00:00
[2022-11-04T21:45:30.643+0000] {standard_task_runner.py:55} INFO - Started process 2320 to run task
[2022-11-04T21:45:30.646+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'orquestation', 'task1', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/5.1-orquestacion.py', '--cfg-path', '/tmp/tmpgzwbjocr']
[2022-11-04T21:45:30.647+0000] {standard_task_runner.py:83} INFO - Job 375: Subtask task1
[2022-11-04T21:45:30.708+0000] {task_command.py:376} INFO - Running <TaskInstance: orquestation.task1 scheduled__2022-05-31T00:00:00+00:00 [running]> on host 643e334f405f
[2022-11-04T21:45:30.780+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=orquestation
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-31T00:00:00+00:00
[2022-11-04T21:45:30.781+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-04T21:45:30.782+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'task1'"]
[2022-11-04T21:45:30.794+0000] {subprocess.py:86} INFO - Output:
[2022-11-04T21:45:32.797+0000] {subprocess.py:93} INFO - task1
[2022-11-04T21:45:32.798+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-11-04T21:45:32.824+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=orquestation, task_id=task1, execution_date=20220531T000000, start_date=20221104T214530, end_date=20221104T214532
[2022-11-04T21:45:32.867+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-04T21:45:32.910+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
