[2022-11-04T17:29:52.352+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.367+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.368+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.369+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:29:52.370+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.389+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-02 00:00:00+00:00
[2022-11-04T17:29:52.397+0000] {standard_task_runner.py:55} INFO - Started process 2095 to run task
[2022-11-04T17:29:52.400+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmp01pkqgbr']
[2022-11-04T17:29:52.401+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask hello_Custom-Operator
[2022-11-04T17:29:52.483+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:29:52.577+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-04T17:29:52.578+0000] {taskinstance.py:1851} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2022-11-04T17:29:52.591+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221102T000000, start_date=20221104T172952, end_date=20221104T172952
[2022-11-04T17:29:52.609+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task hello_Custom-Operator (execute() got an unexpected keyword argument 'context'; 2095)
[2022-11-04T17:29:52.653+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-04T17:29:52.675+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-04T17:36:14.785+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-04T17:36:14.804+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-04T17:36:14.804+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:14.805+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:36:14.805+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:14.834+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-02 00:00:00+00:00
[2022-11-04T17:36:14.844+0000] {standard_task_runner.py:55} INFO - Started process 2402 to run task
[2022-11-04T17:36:14.847+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpb052wrzg']
[2022-11-04T17:36:14.848+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask hello_Custom-Operator
[2022-11-04T17:36:15.064+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-02T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:36:15.203+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-04T17:36:15.204+0000] {logging_mixin.py:120} INFO - Hi Freddy M
[2022-11-04T17:36:15.214+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221102T000000, start_date=20221104T173614, end_date=20221104T173615
[2022-11-04T17:36:15.261+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-04T17:36:15.295+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
