[2022-11-04T17:29:52.259+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.277+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.278+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.279+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:29:52.280+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.311+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-01 00:00:00+00:00
[2022-11-04T17:29:52.327+0000] {standard_task_runner.py:55} INFO - Started process 2094 to run task
[2022-11-04T17:29:52.330+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpw85a_3en']
[2022-11-04T17:29:52.333+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask hello_Custom-Operator
[2022-11-04T17:29:52.410+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:29:52.501+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2022-11-04T17:29:52.502+0000] {taskinstance.py:1851} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2022-11-04T17:29:52.515+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221101T000000, start_date=20221104T172952, end_date=20221104T172952
[2022-11-04T17:29:52.534+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task hello_Custom-Operator (execute() got an unexpected keyword argument 'context'; 2094)
[2022-11-04T17:29:52.544+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-04T17:29:52.567+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-04T17:36:14.731+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-04T17:36:14.756+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [queued]>
[2022-11-04T17:36:14.758+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:14.759+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:36:14.761+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:14.792+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-01 00:00:00+00:00
[2022-11-04T17:36:14.801+0000] {standard_task_runner.py:55} INFO - Started process 2401 to run task
[2022-11-04T17:36:14.804+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmp34q0v9ji']
[2022-11-04T17:36:14.805+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask hello_Custom-Operator
[2022-11-04T17:36:15.008+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-01T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:36:15.149+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-01T00:00:00+00:00
[2022-11-04T17:36:15.150+0000] {logging_mixin.py:120} INFO - Hi Freddy M
[2022-11-04T17:36:15.161+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221101T000000, start_date=20221104T173614, end_date=20221104T173615
[2022-11-04T17:36:15.217+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-04T17:36:15.246+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
