[2022-11-08T17:52:21.027+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6-monitoring_1.task2 scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-11-08T17:52:21.059+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 6-monitoring_1.task2 scheduled__2022-01-16T00:00:00+00:00 [queued]>
[2022-11-08T17:52:21.060+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T17:52:21.063+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-08T17:52:21.064+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-08T17:52:21.114+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task2> on 2022-01-16 00:00:00+00:00
[2022-11-08T17:52:21.136+0000] {standard_task_runner.py:55} INFO - Started process 762 to run task
[2022-11-08T17:52:21.142+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '6-monitoring_1', 'task2', 'scheduled__2022-01-16T00:00:00+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/6.1-monitoring.py', '--cfg-path', '/tmp/tmpma0qzmf5']
[2022-11-08T17:52:21.144+0000] {standard_task_runner.py:83} INFO - Job 428: Subtask task2
[2022-11-08T17:52:21.439+0000] {task_command.py:376} INFO - Running <TaskInstance: 6-monitoring_1.task2 scheduled__2022-01-16T00:00:00+00:00 [running]> on host 638485efabe7
[2022-11-08T17:52:21.622+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=6-monitoring_1
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2022-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-16T00:00:00+00:00
[2022-11-08T17:52:21.651+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-08T17:52:21.654+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "sleep 2 && echo 'task2!"]
[2022-11-08T17:52:21.690+0000] {subprocess.py:86} INFO - Output:
[2022-11-08T17:52:21.859+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2022-11-08T17:52:21.865+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2022-11-08T17:52:21.867+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-11-08T17:52:21.906+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-11-08T17:52:21.960+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=6-monitoring_1, task_id=task2, execution_date=20220116T000000, start_date=20221108T175221, end_date=20221108T175221
[2022-11-08T17:52:22.018+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 428 for task task2 (Bash command failed. The command returned a non-zero exit code 2.; 762)
[2022-11-08T17:52:22.047+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-08T17:52:22.175+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
